from enum import Enum


class Action(Enum):  # 16 действий максимум
    ON_MOVE = 1
    ON_CLICK_RELEASED_LEFT = 2
    ON_CLICK_PRESSED_LEFT = 3
    ON_CLICK_RELEASED_RIGHT = 4
    ON_CLICK_PRESSED_RIGHT = 5
    ON_CLICK_RELEASED_MIDDLE = 6
    ON_CLICK_PRESSED_MIDDLE = 7
    ON_SCROLL = 8
    ON_PRESS_REGULAR = 9
    ON_PRESS_SPECIAL = 10
    ON_RELEASE_REGULAR = 11
    ON_RELEASE_SPECIAL = 12


XY_ACTIONS = (
    Action.ON_MOVE,
    Action.ON_CLICK_RELEASED_LEFT,
    Action.ON_CLICK_RELEASED_RIGHT,
    Action.ON_CLICK_PRESSED_LEFT,
    Action.ON_CLICK_PRESSED_RIGHT,
)

SCROLL_ADDITIONAL_VALUE = 1024
